@TodoApi_HostAddress = https://localhost:7292

Post {{TodoApi_HostAddress}}/todoitems
Content-Type: application/json

{
  "name":"walk dog",
  "isComplete":true
}

###

Get {{TodoApi_HostAddress}}/todoitems

###

GET {{TodoApi_HostAddress}}/todoitems/1

###